#%RAML 1.0
title: sw-orders-sapi-raml
baseUri: http://localhost:8081
mediaType: 
- application/json

types:
  Order: !include datatypes/Order.raml
  OrderItem: !include datatypes/OrderItem.raml
  OrderRequest: !include datatypes/OrderRequest.raml
  ErrorMessage: !include datatypes/ErrorMessage.raml

resourceTypes:
  collection: !include resourceTypes/collection.raml
  member: !include resourceTypes/member.raml

traits:
  Pageable: !include traits/Pageable.raml

/customers:
  /{id}:
    /orders: 
      type: collection
           
      get:
    
          
/orders:
 type: collection
 post:   
 get:
   is: [Pageable]
 /{id}:
   type: member     
   get:
   delete:
    
     
     
     
   